export enum title {
  welcome_back = 'Welcome back,',
  signin_to_continue = 'Sign in to continue',
  welcome_to_mi_salon = 'Welcome to MI Salon',
  create_your_account = 'Create your account',
  first_name = 'First Name',
  last_name = 'Last Name',
  email_address = 'Email Address',
  phone_number = 'Phone Number',
  password = 'Password',
  confirm_password = 'Confirm Password',
  forgot_password = 'Forgot Password',
  enter_forgot_password_email = 'Please enter the email you used at the time of registration to get the password reset instructions.',
  verification_code = 'Verification Code',
  confirm_otp = 'Confirm your account by entering the OTP code sent by email.',
  change_password = 'Change Password',
  my_account = 'My Account',
  edit_profile = 'Edit Profile',
  full_name = 'Full Name',
  old_password = 'Old Password',
}
