// Auth User
export const UPDATE_USER_IS_LOGGED_IN = 'UPDATE_IS_LOGGED_IN';
export const UPDATE_FORGOT_PASSWORD_EMAIL = 'UPDATE_FORGOT_PASSWORD_EMAIL';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';

// Create Appointment

export const UPDATE_SELECTED_SALON = 'UPDATE_SELECTED_SALON';
export const UPDATE_SELECTED_TREATMENT = 'UPDATE_SELECTED_TREATMENT';
export const UPDATE_SELECTED_BARBER = 'UPDATE_SELECTED_BARBER';
export const UPDATE_SELECTED_DATE = 'UPDATE_SELECTED_DATE';
export const UPDATE_SELECTED_TIME = 'UPDATE_SELECTED_TIME';
export const CLEAR_APPOINTMENT_DATA = 'CLEAR_APPOINTMENT_DATA';

// Ui
export const UPDATE_SELECTED_TAB = 'UPDATE_SELECTED_TAB';
